name: me.sushka.dev

title: me.sushka.dev
description: my links

version: v0.1

baseurl: ""
permalink: /:slug/

plugins:
  - jekyll-redirect-from

collections:
  urls:
    output: true
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls
